name: Vue.js

on:
  push:
    tags:
      - 'v*'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Node Dependecies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}:latest

      - name: Deploy To Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            set -e

            IMAGE=ghcr.io/nazarkurii/marshrutka_customer_ui:latest
            OLD_CONTAINER=customer_ui
            NEW_CONTAINER=customer_ui_latest
            NETWORK=marshrutka_net

            cd ~/marshrutka/deployment
            git pull origin main || true

            if ! docker network inspect $NETWORK >/dev/null 2>&1; then
              docker network create $NETWORK
            fi

            docker pull $IMAGE
            docker run -d \
              --network $NETWORK \
              --name $NEW_CONTAINER \
              $IMAGE

            COUNT=0
            MAX_TRIES=10


            while true; do
              STATUS=$(docker inspect --format='{{.State.Health.Status}}' $NEW_CONTAINER 2>/dev/null || echo "starting")

              if [ $STATUS = "healthy" ]; then
                break
              fi

              COUNT=$((COUNT+1))

              echo "Status:"
              echo $STATUS

              if [ $COUNT -ge $MAX_TRIES]; then
                echo "Health check failed"
                docker logs $NEW_CONTAINER || true
                docker rm -f $NEW_CONTAINER || true
                docker image prune -f -a || true
                exit 1
              fi

              sleep 3
            done

            docker network disconnect $NETWORK $OLD_CONTAINER || true
            docker stop $OLD_CONTAINER || true
            docker rm $OLD_CONTAINER || true

            docker rename $NEW_CONTAINER $OLD_CONTAINER

            docker restart nginx

            docker container prune -f
            docker image prune -a -f
